### ISSUE TITLE
Update search docs to reflect changes to institutional search

### ISSUE THREAD

**Issue by anvit** [artefactual/atom-docs#236]
See https://github.com/artefactual/atom/issues/1635.
Changes required at: https://accesstomemory.org/en/docs/2.7/user-manual/access-content/search-atom/#search-box-delimiters

**Comment by fiver-watson** [comment]
I mean....

Important note: ALL the documentation images still show the old BS2 user interface. Since you are ultimately changing the BS5 institutional search feature to be almost the same as it was in BS2, it seems that the real big task for 2.8 is to update all the screenshots to show BS5 elements. 

This will be a big undertaking, so since 2.8 will make BS5 the default and deprecate (but keep) BS2, I would suggest that it makes sense for someone to start on this now / soon, as picking away at it may take until the 2.9 release anyway...

Just a thought!

**Comment by anvit** [comment]
We'd actually decided to not go with trying to mirror the BS2 search bar due to some accessibility concerns when using keyboard navigation, and just decided to make the Global Search option the default. But yeah, point taken about updating the docs showing BS5 screenshots across all pages. Let me create another issue for that and I'll try to get started on it next week!
